import React from 'react';

const Login = () => {
    return (
        <>
            <Head>
                <title>Exploring Nextjs - About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Login</h1>
        </>
    );
};

export default Login;